import {database} from './database';
import {seal,unseal} from './auth';
export type DriveConnection={refreshToken:string;folderId:string;email:string};
export async function getDriveConnection(){const row=await database().prepare("SELECT value FROM app_settings WHERE key='drive'").first<{value:string}>();if(!row)throw new Error('Chưa kết nối Google Drive.');return JSON.parse(unseal(row.value)) as DriveConnection}
export async function saveDriveConnection(value:DriveConnection){await database().prepare("INSERT INTO app_settings(key,value) VALUES ('drive',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(seal(JSON.stringify(value))).run()}
export async function accessToken(){const c=await getDriveConnection(),r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID||'',client_secret:process.env.GOOGLE_CLIENT_SECRET||'',refresh_token:c.refreshToken,grant_type:'refresh_token'}),cache:'no-store',signal:AbortSignal.timeout(15000)});const d=await r.json();if(!r.ok||!d.access_token)throw new Error('Kết nối Google hết hạn. Hãy kết nối lại Drive.');return {token:String(d.access_token),connection:c}}
export async function driveFetch(path:string,init:RequestInit={},token?:string){const auth=token||(await accessToken()).token;return fetch('https://www.googleapis.com/'+path,{...init,headers:{...Object.fromEntries(new Headers(init.headers)),Authorization:'Bearer '+auth},cache:'no-store',signal:init.signal||AbortSignal.timeout(30000)})}
export async function driveJson(path:string,init:RequestInit={},token?:string){const r=await driveFetch(path,init,token);if(!r.ok)throw new Error(`Google Drive trả về lỗi ${r.status}.`);return r.json()}
export async function attachmentMetadata(id:string){return driveJson('drive/v3/files/'+encodeURIComponent(id)+'?fields=id,name,size,parents,trashed,appProperties') as Promise<{id:string;name:string;size:string;parents?:string[];trashed:boolean;appProperties?:Record<string,string>}>}
export function bucket(){return {async get(id:string){const r=await driveFetch('drive/v3/files/'+encodeURIComponent(id)+'?alt=media');if(r.status===404)return null;if(!r.ok||!r.body)throw new Error(`Không tải được tệp từ Drive (${r.status}).`);return {body:r.body}},async delete(id:string){const r=await driveFetch('drive/v3/files/'+encodeURIComponent(id),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({trashed:true})});if(!r.ok&&r.status!==404)throw new Error('Không chuyển được tệp cũ vào Thùng rác Drive.')}}}
