'use client';
import './settings.css';
import {useEffect,useState} from 'react';
type Status={admin:boolean;database?:boolean;drive?:{email:string;folderId:string}|null};
export default function Settings(){
 const [status,setStatus]=useState<Status|null>(null),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const r=await fetch('/api/admin/session',{cache:'no-store'});if(!r.ok)throw new Error('Không đọc được trạng thái kết nối.');setStatus(await r.json())}catch(e){setMessage(e instanceof Error?e.message:'Không tải được cấu hình.')}}
 useEffect(()=>{void load();setMessage(new URLSearchParams(window.location.search).get('message')||'')},[]);
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const r=await fetch('/api/admin/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})}),d=await r.json();if(!r.ok)throw new Error(d.error||'Không đăng nhập được.');setPassword('');await load()}catch(e){setMessage(e instanceof Error?e.message:'Không đăng nhập được.')}finally{setBusy(false)}}
 async function logout(){setBusy(true);try{const r=await fetch('/api/admin/session',{method:'DELETE'});if(!r.ok)throw new Error('Không đăng xuất được.');await load()}catch(e){setMessage(e instanceof Error?e.message:'Lỗi đăng xuất.')}finally{setBusy(false)}}
 return <main className="settings-page"><a href="/">Về sổ văn bản</a><h1>Quản trị & kết nối</h1><p>Thông tin văn bản lưu ở Supabase. Tệp đính kèm lưu trong Google Drive cá nhân đã kết nối.</p>{message&&<p role="status" className="settings-message">{message}</p>}{!status?<p>Đang kiểm tra…</p>:!status.admin?<form onSubmit={login}><h2>Đăng nhập quản trị</h2><label>Mật khẩu quản trị<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary" disabled={busy}>{busy?'Đang đăng nhập…':'Đăng nhập'}</button><p>Mật khẩu do người triển khai thiết lập. Không dùng mật khẩu Gmail.</p></form>:<><section><h2>Cơ sở dữ liệu Supabase</h2><p>{status.database?'Đã kết nối cơ sở dữ liệu.':'Chưa kết nối được. Kiểm tra DATABASE_URL và chạy tệp SQL theo README.'}</p></section><section><h2>Google Drive</h2>{status.drive?<><p>Đã cấu hình tài khoản <strong>{status.drive.email}</strong>.</p><p><a href={'https://drive.google.com/drive/folders/'+encodeURIComponent(status.drive.folderId)} target="_blank" rel="noreferrer">Mở thư mục văn thư trên Drive</a></p><p>Nếu quyền Google hết hạn, kết nối lại cùng tài khoản. Các tệp đã lưu được giữ nguyên.</p></>:<p>Kết nối lần đầu sẽ tạo thư mục “Văn thư trường học” trong Drive của bạn.</p>}<a className="primary" href="/api/drive/connect">{status.drive?'Kết nối lại Google Drive':'Kết nối Google Drive'}</a></section><div className="settings-actions"><a href="/" className="primary">Mở sổ văn bản</a><button className="secondary" disabled={busy} onClick={logout}>Đăng xuất</button></div></>}</main>
}
