import {createHash,timingSafeEqual} from 'node:crypto';
import {database} from '@/lib/database';
import {sameOrigin,sign,sessionCookie,isAdmin,requireAdmin} from '@/lib/auth';
import {getDriveConnection} from '@/lib/drive';
import {failure} from '@/lib/storage';
export const dynamic='force-dynamic';
export async function GET(r:Request){const admin=isAdmin(r);if(!admin)return Response.json({admin:false},{headers:{'Cache-Control':'no-store'}});try{await database().prepare('SELECT 1 AS ok').first();let drive=null;try{const c=await getDriveConnection();drive={email:c.email,folderId:c.folderId}}catch{}return Response.json({admin:true,database:true,drive},{headers:{'Cache-Control':'no-store'}})}catch{return Response.json({admin:true,database:false,drive:null},{headers:{'Cache-Control':'no-store'}})}}
export async function POST(r:Request){try{if(!sameOrigin(r))return new Response(null,{status:403});if(!process.env.ADMIN_PASSWORD||process.env.ADMIN_PASSWORD.length<24)throw new Error('ADMIN_PASSWORD cần ít nhất 24 ký tự.');if(Number(r.headers.get('content-length'))>4096)return new Response(null,{status:413});const {password}=await r.json();if(typeof password!=='string'||password.length>256)return new Response(null,{status:400});const ip=r.headers.get('x-forwarded-for')?.split(',')[0]?.trim()||'local';const key=createHash('sha256').update(ip).digest('hex');const row=await database().prepare("INSERT INTO login_attempts(key,attempts) VALUES (?,1) ON CONFLICT(key) DO UPDATE SET attempts=CASE WHEN login_attempts.window_start<now()-interval '15 minutes' THEN 1 ELSE login_attempts.attempts+1 END,window_start=CASE WHEN login_attempts.window_start<now()-interval '15 minutes' THEN now() ELSE login_attempts.window_start END RETURNING attempts").bind(key).first<{attempts:number}>();if((row?.attempts||0)>10)return Response.json({error:'Thử đăng nhập quá nhiều lần. Vui lòng chờ 15 phút.'},{status:429,headers:{'Retry-After':'900'}});const digest=(s:string)=>createHash('sha256').update(s).digest();if(!timingSafeEqual(digest(password),digest(process.env.ADMIN_PASSWORD)))return Response.json({error:'Mật khẩu không đúng.'},{status:401});await database().prepare('DELETE FROM login_attempts WHERE key=?').bind(key).run();return Response.json({ok:true},{headers:{'Set-Cookie':sessionCookie('office_admin',sign({role:'admin'},43200),43200),'Cache-Control':'no-store'}})}catch(e){return failure(e)}}
export async function DELETE(r:Request){const denied=requireAdmin(r);if(denied)return denied;return Response.json({ok:true},{headers:{'Set-Cookie':sessionCookie('office_admin','',0)}})}
